version: "3.9"

services:
  db:
    image: postgres:16
    container_name: projekt_db
    environment:
      POSTGRES_USER: projektuser
      POSTGRES_PASSWORD: projektpass
      POSTGRES_DB: projektdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
